# name: try {} catch () {}
# key: try
# --
try
{
    $0
}
catch (${1:const std::exception& e})
{
}
